Telcoin-Association/telcoin-network

crates/execution/faucet/src/lib.rs
crates/execution/faucet/tests/it/faucet.rs
etc/test-and-attest.sh

This moves some of the test ignored because they needed some credentials, etc to make cargo test work out of box for contributors to make attest.  These can only be run by a core dev with credentials anyway so make sure they get run at some point.
Closes issue 178 https://github.com/Telcoin-Association/telcoin-network/issues/178

Run some tests that require credentials during attestation.

---

crates/consensus/primary/src/consensus/mod.rs
crates/consensus/primary/src/consensus/state.rs
etc/local-testnet.sh

https://github.com/Telcoin-Association/telcoin-network/issues/186
Closes the gap on being able to restart after deleting all data.  Note all data includes these dirs:
static_files/
db/
consensus-db/
Not removing all will lead to issues.  This should also apply later to add a new validator after he chain is started.

Last fixes to allow startup of a validator with an empty DB.

---

crates/consensus/executor/src/subscriber.rs
crates/consensus/primary/src/consensus/mod.rs
crates/consensus/primary/src/consensus/state.rs
crates/consensus/primary/src/consensus/tests/bullshark_tests.rs
crates/consensus/primary/src/consensus_bus.rs
crates/consensus/primary/src/synchronizer.rs
crates/consensus/primary/src/tests/synchronizer_tests.rs
crates/state-sync/src/lib.rs

- Separate gc and committed rounds into different watch channels
- helper method for consensus_bus to `update_consensus_rounds` that sends on both gc/committed round watch channels
- progress towards separating synchronizer
- also supports `borrow_and_update()` now since single consumer for each watch channel
- previously it was only safe to call `borrow` because some watchers needed the commit round while others needed the gc round. this separates the two

separate watch channels for committed round updates and gc round updates

---

crates/consensus/executor/src/subscriber.rs
crates/consensus/primary/src/certificate_fetcher.rs
crates/consensus/primary/src/consensus/state.rs
crates/consensus/primary/src/consensus/tests/bullshark_tests.rs
crates/consensus/primary/src/consensus_bus.rs
crates/consensus/primary/src/synchronizer.rs
crates/consensus/primary/src/tests/synchronizer_tests.rs
crates/state-sync/src/lib.rs

- separate consensus round watch channels into separate commit round and gc round updates
- allows watch channels to `borrow_and_update`
- addresses concerns raised in #201 and #202 by keeping rounds in watch channels u32

Separate Committed/GC Round Updates

---

Cargo.lock
crates/consensus/consensus-metrics/Cargo.toml
crates/consensus/primary/Cargo.toml
crates/consensus/primary/src/aggregators/certificates.rs
crates/consensus/primary/src/aggregators/mod.rs
crates/consensus/primary/src/synchronizer.rs
crates/execution/batch-builder/src/lib.rs

- refactor certificates aggregator for synchronizer to compartmentalize logic better
- remove unused deps and cleanup comments I found while grepping `dashmap`

certificates aggregator to reduce synchronizer logic

---

Cargo.toml
crates/engine/src/lib.rs
crates/engine/src/payload_builder.rs
crates/execution/batch-validator/src/validator.rs
crates/execution/node-traits/src/engine.rs
crates/types/src/primary/header.rs
crates/types/src/primary/output.rs
etc/Dockerfile

- rename `ConsensusOutputDigest` -> `ConsensusDigest`
- remove old todos
- build execution blocks off consensus header instead of consensus output

Engine Cleanup

---

Cargo.lock
crates/consensus/executor/Cargo.toml
crates/consensus/executor/src/subscriber.rs
crates/consensus/primary/src/consensus/tests/consensus_tests.rs
crates/consensus/primary/src/network/mod.rs
crates/consensus/primary/src/tests/primary_tests.rs
crates/engine/src/lib.rs
crates/execution/batch-builder/src/lib.rs
crates/execution/batch-builder/tests/it/batch_builder.rs
crates/network-types/src/lib.rs
crates/test-utils/src/committee.rs
crates/types/src/primary/block.rs
crates/types/src/primary/output.rs

- add an extra 32-byte field to ConsensusHeader for experimenting on testnet (may be removed or repurposed later)
- subscriber unit test
- test utils

add extra 32-byte field to consensus header/output

---

bin/telcoin-network/src/cli.rs
crates/consensus/primary/src/certificate_fetcher.rs
crates/consensus/primary/src/consensus/mod.rs
crates/consensus/primary/src/consensus/state.rs
crates/consensus/primary/src/consensus/tests/bullshark_tests.rs
crates/consensus/primary/src/error/proposer.rs
crates/consensus/primary/src/network/handler.rs
crates/consensus/primary/src/network/message.rs
crates/consensus/primary/src/network/mod.rs
crates/consensus/primary/src/proposer.rs
crates/consensus/primary/src/state_sync/cert_manager.rs
crates/consensus/primary/src/state_sync/cert_validator.rs
crates/consensus/worker/src/batch_fetcher.rs
crates/consensus/worker/src/network/handler.rs
crates/consensus/worker/src/network/message.rs
crates/consensus/worker/src/network/mod.rs
crates/engine/src/error.rs
crates/execution/batch-builder/src/error.rs
crates/network-libp2p/src/codec.rs
crates/network-libp2p/src/error.rs
crates/types/src/worker/sealed_batch.rs

Addresses comment on last PR stack.
- When requesting batches from any peer divide the list up instead of request all batches from all peers.
- Remove the batch response type, the extra field could not be trusted and was never used so just return the vector of batches we could get which may or may not be complete.  All the higher level code already assumed this.

Better batch fetching.

---

crates/consensus/primary/src/consensus_bus.rs
crates/consensus/worker/src/network/handler.rs
crates/consensus/worker/src/network/mod.rs
crates/consensus/worker/src/tests/batch_provider_tests.rs
crates/consensus/worker/src/worker.rs
crates/execution/batch-builder/src/lib.rs
crates/execution/batch-builder/tests/it/batch_builder.rs
crates/execution/faucet/tests/it/faucet.rs
crates/types/src/sync.rs

This is useful for non-CVVs to preemptively get batches.
- A worker will publish a batch hash after it has been accepted by the committee.
- Other nodes will confirm the gossip originated with the committee to help avoid any spoofing.
- Snuck a tiny consensus bus refactor in, no need to hold onto broadcast channel receivers, don't worry about not having anyone to send to.
This supports https://github.com/Telcoin-Association/telcoin-network/issues/149

Publish and use batch gossip.

---

crates/config/src/consensus.rs
crates/config/src/network.rs
crates/consensus/primary/src/network/mod.rs
crates/consensus/worker/src/network/mod.rs
crates/network-libp2p/src/consensus.rs
crates/network-libp2p/src/peers/all_peers.rs
crates/network-libp2p/src/peers/banned.rs
crates/network-libp2p/src/peers/behavior.rs
crates/network-libp2p/src/peers/manager.rs
crates/network-libp2p/src/peers/peer.rs
crates/network-libp2p/src/tests/banned_peers.rs
crates/network-libp2p/src/tests/common.rs
crates/network-libp2p/src/tests/network_tests.rs
crates/network-libp2p/src/tests/peer_manager.rs
crates/network-libp2p/src/tests/peers.rs
crates/network-libp2p/src/types.rs
crates/node/src/lib.rs
crates/types/src/worker/info.rs

- use `String` for topics to support Eq/Ord traits
- refactor authorized publishers as a map to support different publishers per topic

Subcribe to Topics

---

crates/network-libp2p/src/peers/cache.rs
crates/network-libp2p/src/tests/cache_peers.rs
crates/network-libp2p/src/tests/peer_manager.rs
crates/network-libp2p/src/tests/peers.rs

- fix unit tests that would generate a ipv4 addr ~80% of the time
- take time sooner for cache tests to limit sporadic failures when timestamp accuracy > 20ms

PATCH: refactor tests after sporadic failure

---

Cargo.lock
bin/telcoin-network/tests/it/genesis_tests.rs
crates/config/Cargo.toml
crates/consensus/executor/src/subscriber.rs
crates/engine/src/lib.rs
crates/engine/src/payload_builder.rs
crates/execution/batch-builder/src/batch.rs
crates/execution/batch-builder/src/lib.rs
crates/execution/batch-builder/src/test_utils.rs
crates/execution/batch-builder/tests/it/batch_builder.rs
crates/network-libp2p/src/tests/cache_peers.rs
crates/tn-reth/Cargo.toml
crates/tn-reth/src/error.rs
crates/tn-reth/src/lib.rs
crates/tn-reth/src/system_calls.rs
crates/tn-reth/src/traits.rs
crates/types/src/primary/output.rs
crates/types/src/worker/pending_batch.rs

- add closing epoch field to consensus output
- support for calling `concludeEpoch` on consensus registry contract
- simple fischer-yates shuffle algo based on leader cert's aggregate BLS signature and chacharand8
- update genesis tests to use main sol interface
- rename `block` -> `batch` leftovers
The `close_epoch` field is always set to `false` on consensus output so the closing epoch is never called. This will be addressed in a follow-up PR.

Conclude Epoch System Call

---

bin/telcoin-network/tests/it/restarts.rs
crates/consensus/primary/src/network/mod.rs
crates/consensus/worker/src/network/mod.rs
crates/node/src/lib.rs
crates/state-sync/src/lib.rs
crates/test-utils/src/execution.rs
crates/tn-reth/src/lib.rs

This is primarily to improve the restart tests.  Includes two other "fixes" that seemed to improve the test reliability.
- When starting the node will progress once it can connect with one primary peer.  This is a lot looser then than the old code that expected a node to be in the committee and was also buggy which I believe occasionally derailed restart tests.
- The Reth DB (not used except to pass to Reth) is created early and not recreated on a node "restart" (currently used when a validator has caught up to rejoin consensus).  MDBX was occasionally freaking out when the DB was dropped and quickly recreated.  The consensus DB is also managed this way, always has been.  Forget specific reasons but probably similar.  There may be MDBX issues in general, have been seeing testnet issues …

Retry test fixes.

---

crates/consensus/consensus-metrics/src/lib.rs
crates/consensus/executor/src/subscriber.rs
crates/consensus/primary/src/network/handler.rs
crates/consensus/primary/src/network/mod.rs
crates/consensus/primary/src/tests/network_tests.rs
crates/consensus/primary/src/tests/primary_tests.rs
crates/node/src/manager.rs
crates/state-sync/src/lib.rs
crates/types/src/task_manager.rs

- rename the cloneable task manager type to spawn tasks

`TaskManagerClone` -> `TaskSpawner`

---

Cargo.lock
crates/network-libp2p/Cargo.toml
crates/network-libp2p/src/consensus.rs
crates/network-libp2p/src/peers/manager.rs
crates/network-libp2p/src/tests/network_tests.rs
crates/network-libp2p/src/types.rs
crates/types/src/crypto/bls_signature.rs

This adds kademlia to the network stack for peer discovery.  It seems to work but better hooks and tests will be incoming.  It also publishes a signed record keyed on a nodes BLS key.  Not used yet but this will allow nodes to change network setting/keys and still be located by their BLS key.

Initial addition of kademlia to network for peer discovery.

---

bin/telcoin-network/src/genesis/mod.rs
bin/telcoin-network/src/keytool/generate.rs
bin/telcoin-network/src/keytool/mod.rs
bin/telcoin-network/tests/it/restarts.rs
bin/telcoin-network/tests/it/util/mod.rs
crates/node/src/manager.rs
etc/local-testnet.sh

Makes configuring an observer more straightforward.  Adds a restart test to make sure an observer is participating in a network and adds an observer to the local testate script.
Also updated tn-contracts, I needed to pull master for something and this happened...

Observer tests and config.

---

crates/consensus/worker/src/batch_fetcher.rs
crates/consensus/worker/src/network/mod.rs
crates/consensus/worker/src/quorum_waiter.rs
crates/consensus/worker/src/tests/quorum_waiter_tests.rs
crates/node/src/manager.rs

- use `TaskSpawner` for worker
- update at epoch boundary

spawn worker tasks with task spawner

---

Cargo.lock
bin/telcoin-network/tests/it/faucet.rs
bin/telcoin-network/tests/it/restarts.rs
crates/consensus/worker/Cargo.toml
crates/consensus/worker/src/lib.rs
crates/consensus/worker/src/network/mod.rs
crates/consensus/worker/src/quorum_waiter.rs
crates/consensus/worker/src/test_utils.rs
crates/consensus/worker/src/tests/batch_provider_tests.rs
crates/consensus/worker/src/tests/quorum_waiter_tests.rs
crates/consensus/worker/src/worker.rs
crates/execution/batch-builder/Cargo.toml
crates/execution/batch-builder/src/lib.rs
crates/execution/batch-builder/tests/it/build_batches.rs
crates/execution/faucet/tests/it/faucet.rs
crates/network-libp2p/src/consensus.rs
crates/network-libp2p/src/tests/network_tests.rs
crates/node/src/engine/inner.rs
crates/node/src/engine/mod.rs
crates/node/src/manager.rs
crates/tn-reth/src/lib.rs

- replace `tokio::spawn` with dedicated task spawners owned by task managers

Spawn all tasks through `TaskManager`s

---

bin/telcoin-network/src/genesis/add_validator.rs
bin/telcoin-network/src/genesis/create_committee.rs
bin/telcoin-network/src/genesis/mod.rs
bin/telcoin-network/src/genesis/validate.rs
bin/telcoin-network/src/keytool/generate.rs
bin/telcoin-network/src/keytool/mod.rs
bin/telcoin-network/tests/it/faucet.rs
bin/telcoin-network/tests/it/genesis_tests.rs
bin/telcoin-network/tests/it/util/mod.rs
crates/config/src/genesis.rs
crates/config/src/keys.rs
crates/config/src/network.rs
crates/config/src/node.rs
crates/config/src/traits.rs
crates/consensus/executor/src/lib.rs
crates/consensus/executor/src/subscriber.rs
crates/consensus/primary/src/consensus_bus.rs
crates/engine/src/lib.rs
crates/engine/tests/it/main.rs
crates/execution/batch-builder/src/lib.rs
crates/node/src/engine/inner.rs
crates/node/src/engine/mod.rs
crates/node/src/manager.rs
crates/node/src/primary.rs
crates/tn-reth/Cargo.toml
crates/tn-reth/src/evm_config.rs
crates/tn-reth/src/lib.rs
crates/types/src/crypto/bls_signature.rs
crates/types/src/crypto/mod.rs
crates/types/src/task_manager.rs

- update epoch manager to fully close epoch at boundary
- move logic to close epoch from subscriber to epoch manager
- use mpsc instead of broadcast for consensus output
- export canonical state stream directly
- follow up PR to address test failures and cleanup

Epoch Transition

---

crates/network-libp2p/src/consensus.rs

- use correct network public key for node records (previously always primary)

Worker KAD Records

---

crates/network-libp2p/src/consensus.rs
crates/node/src/engine/mod.rs
crates/node/src/manager.rs
etc/local-testnet.sh

- Move the metrics service to the node task manager.
- Attempt to wait until the epoch task manager has shutdown before restarting.  This can timeout pretty quickly.
- Fixed a race with the network event_stream during epoch rotation.

Tweak epoch code to hopefully avoid some races.

---

crates/consensus/primary/src/certificate_fetcher.rs
crates/consensus/primary/src/network/handler.rs
crates/consensus/primary/src/network/mod.rs
crates/consensus/primary/src/tests/primary_tests.rs

- sanitize requested max items before allocating memory for vec
- use same limit for all requested certs from peers

Cantina-30: sanitize missing certificates requests

---

crates/batch-validator/src/validator.rs
crates/consensus/worker/src/network/error.rs
crates/types/src/worker/sealed_batch.rs

- use checked addition when validating batches to handle possible u64 gas overflow

Cantina-364: batch validation overflow

---

bin/telcoin-network/tests/it/epochs.rs
bin/telcoin-network/tests/it/genesis_tests.rs
crates/batch-builder/src/lib.rs
crates/batch-builder/tests/it/build_batches.rs
crates/consensus/executor/src/subscriber.rs
crates/consensus/primary/src/consensus/tests/bullshark_tests.rs
crates/consensus/primary/src/consensus/tests/consensus_tests.rs
crates/consensus/primary/src/consensus_bus.rs
crates/consensus/primary/src/network/mod.rs
crates/consensus/primary/src/tests/network_tests.rs
crates/consensus/primary/src/tests/proposer_tests.rs
crates/consensus/worker/src/network/mod.rs
crates/consensus/worker/src/tests/batch_provider_tests.rs
crates/engine/tests/it/main.rs
crates/execution/faucet/tests/it/faucet.rs
crates/network-libp2p/src/consensus.rs
crates/network-libp2p/src/tests/network_tests.rs
crates/network-libp2p/src/types.rs
crates/node/src/lib.rs
crates/node/src/manager.rs
crates/node/tests/it/main.rs
crates/types/src/notifier.rs
crates/types/src/sync.rs
crates/types/src/task_manager.rs

This is intended as a precursor PR to cantina 1045 (and maybe others).  It attempts to close race conditions at the epoch boundaries.
In addition to the consensus_bus lifetime change this PR also fixes the task manager to drop any async tasks it spawned when a TaskManger is dropped.

Initial migration to an application life timed consensus bus.
