crates/consensus/executor/src/errors.rs, crates/consensus/executor/src/subscriber.rs
This is basically a pre-cursor refactor for https://github.com/Telcoin-Association/telcoin-network/issues/191 that should make it easier to move to libp2p as well.
=> Refactor subscriber to support future error handling and libp2p migration.

CONTRIBUTING.md
- update contributing guidelines with renamed make command
=> fix typo in contributors guideline

Cargo.lock, Cargo.toml, Makefile, bin/telcoin-network/Cargo.toml, bin/telcoin-network/src/lib.rs, bin/telcoin-network/src/main.rs, bin/telcoin-network/src/version.rs, etc/Dockerfile
- update dockerfile to fix open-ssl error 
- rm jemalloc 
- fix bin versioning
=> deployment updates

crates/consensus/executor/src/subscriber.rs, crates/engine/src/error.rs, crates/engine/src/lib.rs, crates/engine/src/payload_builder.rs, crates/execution/batch-builder/src/lib.rs, crates/execution/batch-builder/tests/it/batch_builder.rs, crates/node/src/engine/inner.rs, crates/types/src/primary/output.rs
https://github.com/Telcoin-Association/telcoin-network/issues/232
This tests that setting the right flag does not finalize but this we should add some integration tests once we can run "observer" nodes to test this in the wild.
The implementation turned out to be pretty simple and basically contained in the engine.
=> If not a CVV then do not finalize a block until we see it in a certificate.

crates/config/src/network.rs, crates/consensus/primary/src/network/mod.rs, crates/network-libp2p/src/consensus.rs
- adjust network config
- remove application penalty when processing gossip. this will be handled in a follow-up PR
=> V0.3.2 adiri patch

crates/config/src/consensus.rs, crates/consensus/executor/src/subscriber.rs, crates/consensus/primary/src/aggregators/certificates.rs, crates/consensus/primary/src/aggregators/sync.rs, crates/consensus/primary/src/aggregators/votes.rs, crates/consensus/primary/src/certifier.rs, crates/consensus/primary/src/consensus/bullshark.rs, crates/consensus/primary/src/consensus/leader_schedule.rs, crates/consensus/primary/src/consensus/tests/bullshark_tests.rs, crates/consensus/primary/src/consensus/tests/randomized_tests.rs, crates/consensus/primary/src/network/handler.rs, crates/consensus/primary/src/proposer.rs, crates/consensus/primary/tests/certificate_order_test.rs, crates/consensus/worker/src/quorum_waiter.rs, crates/consensus/worker/src/worker.rs, crates/state-sync/src/lib.rs, crates/test-utils/src/authority.rs, crates/test-utils/src/builder.rs, crates/test-utils/src/helpers.rs, crates/types/src/committee.rs, crates/types/src/primary/certificate.rs, crates/types/src/primary/header.rs, crates/types/src/primary/reputation.rs
Basically what the name says, breaking this down into a PR stack for easier review.
This should be fine standalone but will be a base PR.
=> Refactor the committee for interior mutability in prep for epoch support.

crates/consensus/primary/src/tests/certificate_tests.rs, crates/test-utils/src/helpers.rs, crates/test-utils/src/tests/output_tests.rs, crates/types/src/committee.rs, crates/types/src/primary/certificate.rs
- A couple of renames I forgot in my last PR.
- Use an Arc wrapped "inner" for Authority- it is cloned a lot so this should be better.
=> Final small cleanups to committee refactor.

crates/config/src/consensus.rs, crates/config/src/genesis.rs, crates/config/src/network.rs, crates/config/src/traits.rs, crates/consensus/executor/src/subscriber.rs, crates/consensus/executor/tests/consensus_integration_tests.rs, crates/consensus/primary/src/consensus/tests/bullshark_tests.rs, crates/consensus/primary/src/consensus/tests/leader_schedule_tests.rs, crates/consensus/primary/src/tests/cert_collector_tests.rs, crates/consensus/primary/src/tests/cert_manager_tests.rs, crates/consensus/primary/src/tests/certificate_fetcher_tests.rs, crates/consensus/primary/src/tests/certificate_tests.rs, crates/consensus/primary/src/tests/primary_tests.rs, crates/consensus/primary/tests/certificate_order_test.rs, crates/consensus/worker/src/batch_fetcher.rs, crates/node/src/dirs.rs, crates/node/src/lib.rs, crates/test-utils/src/authority.rs, crates/test-utils/src/builder.rs, crates/test-utils/src/temp_dirs.rs, crates/test-utils/src/tests/output_tests.rs, crates/types/src/committee.rs
- load/store config to file
- support custom network configs for testing
- clippy had a lot of changes
=> Support Custom Network Config

crates/config/src/consensus.rs, crates/network-libp2p/src/consensus.rs, crates/network-libp2p/src/peers/all_peers.rs, crates/network-libp2p/src/peers/banned.rs, crates/network-libp2p/src/peers/behavior.rs, crates/network-libp2p/src/peers/manager.rs, crates/network-libp2p/src/peers/peer.rs, crates/network-libp2p/src/tests/banned_peers.rs, crates/network-libp2p/src/tests/common.rs, crates/network-libp2p/src/tests/network_tests.rs, crates/network-libp2p/src/tests/peer_manager.rs, crates/network-libp2p/src/tests/peers.rs, crates/network-libp2p/src/types.rs, crates/node/src/lib.rs, crates/types/src/worker/info.rs
- set committee as trusted peers at the start of each epoch
=> Network: Update Committee

Cargo.toml, README.md, bin/telcoin-network/src/genesis/add_validator.rs, bin/telcoin-network/tests/it/faucet.rs, bin/telcoin-network/tests/it/restarts.rs, clippy.toml, crates/config/src/genesis.rs, crates/config/src/network.rs, crates/config/src/traits.rs, crates/consensus/consensus-metrics/src/histogram.rs, crates/consensus/primary/src/consensus/tests/bullshark_tests.rs, crates/consensus/primary/src/consensus/tests/randomized_tests.rs, crates/consensus/primary/src/tests/cert_validator_tests.rs, crates/consensus/primary/src/tests/certificate_fetcher_tests.rs, crates/consensus/primary/src/tests/primary_tests.rs, crates/execution/faucet/src/cli_ext.rs, crates/execution/faucet/src/lib.rs, crates/execution/faucet/src/service.rs, crates/execution/faucet/tests/it/faucet.rs, crates/network-libp2p/src/codec.rs, crates/network-libp2p/src/peers/manager.rs, crates/network-libp2p/src/tests/common.rs, crates/network-libp2p/src/tests/network_tests.rs, crates/storage/src/stores/certificate_store.rs, crates/tn-reth/src/dirs.rs, crates/types/src/committee.rs, crates/types/src/crypto/bls_public_key.rs, crates/types/src/serde.rs, crates/types/src/worker/info.rs, etc/Dockerfile
- update rust v1.86
- fix clippy
=> Update rust to 1.86

bin/telcoin-network/src/genesis/create_committee.rs, crates/tn-reth/src/lib.rs
- spawn temp runtime to execute committee pre-genesis
=> spawn tokio runtime for create-committee to execute pre-genesis

bin/telcoin-network/src/genesis/create_committee.rs
- spawn runtime to execute pre-genesis when one doesn't already exist (ie - outside of tests)
=> Tokio runtime test issue

bin/telcoin-network/src/node.rs, etc/local-testnet.sh
Add genesis CLI arg to optionally pass genesis config file so that local testnet includes genesis precompiles
=> Add genesis CLI arg to optionally pass genesis config file

Makefile
Fix test-restarts, this undoes some a testing patch...
=> Fix a mistake that got checked into Makefile.

crates/consensus/worker/src/tests/batch_provider_tests.rs, crates/consensus/worker/src/worker.rs, crates/execution/batch-builder/src/lib.rs, crates/execution/batch-builder/tests/it/batch_builder.rs, crates/execution/faucet/tests/it/faucet.rs, crates/node/src/lib.rs, crates/node/src/manager.rs, crates/node/src/primary.rs, crates/node/src/worker.rs, crates/tn-reth/src/lib.rs, crates/types/src/task_manager.rs
- use const names for task managers
- worker task manager for batch builder
=> Task Manager for Worker

crates/consensus/worker/src/tests/batch_provider_tests.rs, crates/consensus/worker/src/worker.rs, crates/execution/batch-builder/src/lib.rs, crates/execution/batch-builder/tests/it/batch_builder.rs, crates/execution/faucet/tests/it/faucet.rs, crates/node/src/lib.rs, crates/node/src/manager.rs, crates/node/src/primary.rs, crates/node/src/worker.rs, crates/tn-reth/src/lib.rs, crates/types/src/task_manager.rs
- Store submanagers as a map to retrieve by name
=> Retrieve TaskManager::submanagers by Name

crates/consensus/primary/src/network/handler.rs, crates/consensus/primary/src/network/mod.rs, crates/consensus/primary/src/tests/network_tests.rs, crates/consensus/primary/src/tests/primary_tests.rs, crates/node/src/manager.rs
- spawn epoch-related network tasks to abort at epoch boundary
=> Primary Network uses TaskManager

crates/consensus/consensus-metrics/src/lib.rs, crates/consensus/primary/src/network/handler.rs, crates/consensus/primary/src/network/mod.rs, crates/consensus/primary/src/tests/network_tests.rs, crates/consensus/primary/src/tests/primary_tests.rs, crates/node/src/manager.rs
- spawn consensus metrics with task manager
=> Spawn ConsensusMetrics with Task Manager

bin/telcoin-network/src/node.rs, crates/config/src/network.rs, crates/consensus/worker/src/network/handler.rs, crates/consensus/worker/src/network/message.rs, crates/consensus/worker/src/network/mod.rs, crates/consensus/worker/src/worker.rs, crates/execution/batch-validator/Cargo.toml, crates/execution/batch-validator/src/validator.rs, crates/network-libp2p/src/consensus.rs, crates/network-libp2p/src/tests/network_tests.rs, crates/network-libp2p/src/types.rs, crates/node/src/manager.rs, crates/tn-reth/src/txn_pool.rs, crates/types/src/worker/sealed_batch.rs, etc/local-testnet.sh
Attempt to disperse transactions to the network if not a committee member.  A CVV should pick up the ten and include it in a batch.
=> Initial code to publish tnxs if not a CVV.

crates/consensus/primary/src/certifier.rs, crates/consensus/primary/src/network/mod.rs, crates/consensus/primary/src/proposer.rs, crates/consensus/primary/src/tests/primary_tests.rs, crates/consensus/worker/src/network/mod.rs, crates/network-libp2p/src/consensus.rs, crates/network-libp2p/src/peers/manager.rs, crates/network-libp2p/src/tests/network_tests.rs, crates/network-libp2p/src/tests/peer_manager.rs, crates/network-libp2p/src/types.rs, crates/node/src/manager.rs, crates/types/src/task_manager.rs
- refactor network and epoch manager so swarm survives but primary/worker networks reset
=> Spawn Consensus Network for Epoch Manager

crates/consensus/consensus-metrics/src/lib.rs, crates/consensus/primary-metrics/src/consensus.rs, crates/consensus/primary/src/certifier.rs, crates/consensus/primary/src/network/mod.rs, crates/consensus/primary/src/proposer.rs, crates/consensus/primary/src/tests/primary_tests.rs, crates/consensus/worker/src/network/mod.rs, crates/network-libp2p/src/consensus.rs, crates/network-libp2p/src/peers/manager.rs, crates/network-libp2p/src/tests/network_tests.rs, crates/network-libp2p/src/tests/peer_manager.rs, crates/network-libp2p/src/types.rs, crates/node/src/manager.rs, crates/types/src/task_manager.rs
- separate shutdown signals for epoch/node manager tasks
=> Epoch manager spawn epoch and node tasks

crates/consensus/consensus-metrics/src/lib.rs, crates/consensus/primary-metrics/src/consensus.rs, crates/consensus/primary/src/certifier.rs, crates/consensus/primary/src/network/mod.rs, crates/consensus/primary/src/tests/primary_tests.rs, crates/consensus/worker/src/network/mod.rs, crates/network-libp2p/src/consensus.rs, crates/network-libp2p/src/peers/manager.rs, crates/network-libp2p/src/tests/network_tests.rs, crates/network-libp2p/src/tests/peer_manager.rs, crates/network-libp2p/src/types.rs, crates/node/src/manager.rs, crates/types/src/task_manager.rs
- spawn critical/non-critical tasks in task manager
=> Critical tasks in TaskManager

crates/consensus/consensus-metrics/src/lib.rs, crates/consensus/primary-metrics/src/consensus.rs, crates/consensus/primary/src/certifier.rs, crates/consensus/primary/src/network/mod.rs, crates/consensus/primary/src/tests/primary_tests.rs, crates/consensus/worker/src/network/mod.rs, crates/network-libp2p/src/consensus.rs, crates/network-libp2p/src/peers/manager.rs, crates/network-libp2p/src/tests/network_tests.rs, crates/network-libp2p/src/tests/peer_manager.rs, crates/network-libp2p/src/types.rs, crates/node/src/manager.rs, crates/types/src/task_manager.rs
- only use `TaskManager`s on epoch manager within runtime
=> Create runtime in launch node

crates/consensus/consensus-metrics/src/lib.rs, crates/consensus/executor/src/subscriber.rs, crates/consensus/primary-metrics/src/consensus.rs, crates/consensus/primary/src/certifier.rs, crates/consensus/primary/src/network/handler.rs, crates/consensus/primary/src/network/mod.rs, crates/consensus/primary/src/tests/network_tests.rs, crates/consensus/primary/src/tests/primary_tests.rs, crates/consensus/worker/src/network/mod.rs, crates/network-libp2p/src/consensus.rs, crates/network-libp2p/src/peers/manager.rs, crates/network-libp2p/src/tests/network_tests.rs, crates/network-libp2p/src/tests/peer_manager.rs, crates/network-libp2p/src/types.rs, crates/node/src/lib.rs, crates/node/src/manager.rs, crates/state-sync/src/lib.rs, crates/types/src/task_manager.rs
- spawn tasks for epoch manager based on epoch responsibility
- node tasks run for the lifetime of the node
- epoch tasks run for the lifetime of the epoch
=> Separate Task Managers for Epoch/Node Related Tasks

Cargo.lock, Cargo.toml
- address three dependabot alerts
- https://github.com/Telcoin-Association/telcoin-network/security/dependabot/12
- https://github.com/Telcoin-Association/telcoin-network/security/dependabot/4
- https://github.com/Telcoin-Association/telcoin-network/security/dependabot/11
- update `Cargo.lock`
=> update tokio and reqwest

Cargo.lock, Cargo.toml, crates/tn-reth/Cargo.toml, crates/tn-reth/src/evm_config.rs, crates/tn-reth/src/lib.rs, crates/tn-reth/src/traits.rs
This is a bunch of Reth config non-sense so we can add to the protocol and not have Reth reject our changes.
=> Infrastructure to take can control of basefees and other rewards.

bin/telcoin-network/tests/it/restarts.rs, bin/telcoin-network/tests/it/util/mod.rs
Due to merge ordering this test is broken on main, fix it.
=> Fix restart observer test.

bin/telcoin-network/src/genesis/mod.rs, crates/config/src/node.rs, crates/node/src/manager.rs, crates/test-utils/src/execution.rs, crates/tn-reth/src/evm_config.rs, crates/tn-reth/src/lib.rs, crates/tn-reth/src/traits.rs, etc/local-testnet.sh
We need to be able to set the base fee address for a chain at genesis, this patch enables that.
=> Allow the basefee address to be set on genesis.

bin/telcoin-network/src/args/utils.rs, bin/telcoin-network/src/genesis/mod.rs, bin/telcoin-network/tests/it/genesis_tests.rs, crates/tn-reth/src/evm/mod.rs, crates/tn-reth/src/lib.rs, crates/tn-reth/src/system_calls.rs, etc/test-and-attest.sh
=> Update tn contracts

Cargo.lock, bin/telcoin-network/Cargo.toml, bin/telcoin-network/src/genesis/mod.rs, chain-configs/testnet/testnet_accounts.yaml, crates/node/src/manager.rs, crates/node/src/primary.rs, crates/test-utils/src/execution.rs, crates/tn-reth/src/evm/block.rs, crates/tn-reth/src/evm/config.rs, crates/tn-reth/src/lib.rs, crates/types/src/committee.rs, crates/types/src/gas_accumulator.rs
Accumulate block leaders and use them to make the system call for rewards.
=> Connect block rewards to epoch closing system call.

Cargo.lock, bin/telcoin-network/Cargo.toml, bin/telcoin-network/tests/it/restarts.rs, chain-configs/README.md, etc/local-testnet.sh
Restart tweaks.  Replaces an old unmaintained json rpc lib.
=> Replace rpc lib and tweaks to restart tests.

crates/config/src/keys.rs
- update iteration count for PBKDF2 encryption
- exceeds [OWASP recommendation](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#pbkdf2)
=> Cantina-1131: update iteration count for PBKDF2 encryption

bin/telcoin-network/tests/it/epochs.rs
This test sometimes just started failing.  This seems to improve things (made a laptop that was in a failing state work).
=> Use procs instead of multiple tokio runtimes for a test that sometimes failed.
